# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/attica': '@latest'
    'frameworks/baloo': '@latest'
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kbookmarks': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/kfilemetadata': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/knewstuff': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/krunner': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/solid': '@latest'
    'frameworks/sonnet': '@latest'
    'frameworks/kunitconversion': '@latest'
    'plasma/plasma-framework': 'kf5'
    'plasma/libksysguard': '@same'
    'plasma/oxygen': '@same'
    'plasma/plasma-workspace': '@same'
    'plasma/powerdevil': '@same'
    'plasma/systemsettings': '@same'
    'plasma/kactivities': '@latest' # Different branch scheme due to formerly being a Framework
    'plasma/kactivities-stats': '@latest' # Different branch scheme due to formerly being a Framework

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/kdelibs4support': '@latest'

Options:
  require-passing-tests-on: [ 'Linux/Qt5', 'FreeBSD/Qt5' ]
