/* config-runtime.h.  Generated by cmake from config-runtime.h.cmake  */

/* media HAL backend compilation */
#undef COMPILE_HALBACKEND

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* type to use in place of socklen_t if not defined */
#define kde_socklen_t socklen_t
