/* config-runtime.h.  Generated by cmake from config-runtime.h.cmake  */

/* media HAL backend compilation */
#undef COMPILE_HALBACKEND

/* Define if you have long long as datatype */
#cmakedefine HAVE_LONG_LONG 1

/* Define to 1 if you have the `nice' function. */
#cmakedefine HAVE_NICE 1

/* Define to 1 if you have the `sigaction' function. */
#cmakedefine HAVE_SIGACTION 1

/* Define to 1 if you have the `sigset' function. */
#cmakedefine HAVE_SIGSET 1

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#cmakedefine HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#cmakedefine HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/*
    On HP-UX, the declaration of vsnprintf() is needed every time !
*/

/* type to use in place of socklen_t if not defined */
#define kde_socklen_t socklen_t
